name: Build jnk App

on:
  workflow_dispatch:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

defaults:
  run:
    shell: bash
    working-directory: ./
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
        name: 'Checkout repository'

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: 'Install Dependencies'
        run: npm install

      - name: 'Check lint errors'
        run: npm run lint

      #   - name: "Run unit test"
      #     run: npm run test:unit:ci

      - name: 'Build code'
        run: npm run build
